### PR TITLE
Implemented customizable filter function

### LINKED ISSUE #94: Allow complex item listing and filtering

### PR DESCRIPTION
**Pull request by tiagoroldao**
Exported Option and SelectComponent, to allow usage in code of public functions
Made Option.value of type `<any>`, rather than `<string>`

Fixes #94

### CODE REVIEW

**Comment by tiagoroldao** [comment]
@basvandenberg I am aware here that changing the item type is a big change, but don't see an immediate reason for the type restriction to `<string>`. Regardless, I hope to hear your opinion on the subject.

**Comment by basvandenberg** [comment]
Hi @tiagoroldao, thanks for your contributions.

See #87 for explanation why value type is restricted to `string`. In short, this is done so that options can be set  by (string) value instead of by (object) reference. Changing the type to `any` is no option for me.

Customizable filtering has in my opinion also low priority. I think that the current filter function is sufficient in most cases. I might consider adding such a feature in a later release, but not in the 1.0 release.

**Comment by tiagoroldao** [comment]
@basvandenberg  couldn't all those problems mentioned be fixed by implementing an identifier parameter (boolean function/string reference to object id) ?

**Comment by basvandenberg** [comment]
I am not sure what you mean exactly. Maybe you could explain with an example? In the following example (from the examples page)
```
<div>
    Value: <strong>{{selectedValues}}</strong>
</div>
<ng-select
    [options]="characters"
    [multiple]="true"
    [(ngModel)]="selectedValues">
</ng-select>
<button
    (click)="selectedValues=['1','3']">
    Select values 1 and 3
</button>
```
Clicking the button selects options with value '1' and '3'. These values are basically ids used to find the options to select. This works with strings, but not with objects.

Mapping ids to objects falls outside the scope of this component in my opinion. This is the user's responsibility. This components lets you select a value (id) by choosing (clicking) a label. What you do with that id is up to you. In your case you would have a mapping from ids to objects to get the object you want.

**Comment by tiagoroldao** [comment]
Actually, scratch that last comment. 

I have to say, I see no problem in accepting values as objects. Users are expected to understand the implications of value vs reference, and a lot of setup code is avoided by always needing to refer to and from IDs.

Changing the example to use objects works exactly as intended:

```javascript
    VALUES_OBJECTS = [{number: '000', name: 'Aech'} ....];

    OPTIONS_OBJECTS = [{value: this.VALUES_OBJECTS[0], label: 'Aech'}, ....];
```

```html
<ng-select
    [options]="OPTIONS_OBJECTS"
    [multiple]="true"
    [(ngModel)]="selectedValues">
</ng-select>
<div class="button-bar">
    <button
        md-raised-button
        (click)="selectedValues=[VALUES_OBJECTS[1],VALUES_OBJECTS[3]]">
        Select values 1 and 3
    </button>
</div>
```

**Comment by basvandenberg** [comment]
>  Users are expected to understand the implications of value vs reference

I agree with that, but it remains a potential source of difficult to trace bugs for which the user, in my opinion, should be protected against. Also, a user might expect that the object is not compared by reference, but by object equality (which in principle is possible, but which could severely affect performance if the objects are big nested structures), which is not the case.

Bottom line is that we have different opinions on this, which is perfectly fine and often happens on such projects. If this is a 'deal-breaker' for you, please feel free to branch off and take another direction.

**Pull request closed without merging**
