### PR TITLE
New feature1.0

### PR DESCRIPTION
**Pull request by shujahm**
1. In my project I wanted to show the value as the label as well for some of the dropdown and for some I need to show the label itself on UI. So for this I added the “showValueAsLabel” which if true will show the value of the dropdown select as the respective label on UI.

2. Also we needed some extra data from the selected element. Right now we just had value and label but I added “extraData” where users can pass extra data that they want access to once the user selects the respective value from dropdown.

### CODE REVIEW

**Comment by shujahm** [comment]
@basvandenberg  I think this feature is quite important and can be really helpful for others too. And definitely adds value to the overall functionality of the component.

**Comment by basvandenberg** [comment]
Hi @shujahm, many thanks for your contribution. However, I don't see this much added value in these features:

1. If labels and values should be the same, you can give them the same values, for example:
```
myLabels = ['a', 'b', 'c', 'd']; // and so on.
myOptions = myLabels.map((label) => {
    return {
        label: label,
        value: label
    };
});
```
2. The value is basically an identifier for your options, you can use this also to identify your extra data. No need to store/include/reference this extra data in this select component. In my opinion this is outside the scope of this component.

p.s. I saw you committed some .idea files as well, such (personal) configuration file should be left out of the git repo.

**Comment by shujahm** [comment]
well its up to but @basvandenberg apart from me other developer has requested for this too. If you dont want to include it in this repo , then I will help the other developers through my github.

**Comment by basvandenberg** [comment]
Hi @shujahm. Sure, this is all open source, so feel free to adjust and redistribute under the conditions of the software license.

I do not exactly understand your explanation, I think I would need some example code to better understand your situation. For now I stick to my decision and will not include it into the repo.

**Pull request closed without merging**
